Fix uint test test_json_format and Solve pep8 msgfmt error
For json format we only need check the json result.

For pep8 error:
xargs: msgfmt: No such file or directory
ERROR: InvocationError for command /bin/bash -c 'find senlinclient..'
http://logs.openstack.org/92/666992/2/gate/openstack-tox-pep8/fdbc082/job-output.txt.gz

We need to add bindep.txt, like neutron:
https://github.com/openstack/neutron/blob/master/bindep.txt#L5

Co-Authored-By: chenker <chen.ke14@zte.com.cn>

Change-Id: Ifb2d2bb3a1043ab1a4c94d30029bb920b4627a31